project:
  type: website
  output-dir: docs

execute:
  engine: python

website:
  title: "Serena Emedeke"
  favicon: images/logo.png

  navbar:
    logo: images/logo.png
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: projects/index.qmd
        text: Projects
      - href: reflection.qmd
        text: Reflection
      - href: contact.qmd
        text: Contact
    right:
      - href: cv/Serena_Emedeke_CV.pdf
        text: CV
        target: _blank
      - icon: github
        href: https://github.com/serena-128
        target: _blank
      - icon: linkedin
        href: https://www.linkedin.com/in/serena-e-606aa122a/
        target: _blank
      - icon: envelope
        href: mailto:serena.emedeke2@mail.dcu.ie

  page-footer:
    left: "© 2026 Serena Emedeke"
    right: "Built with Quarto"

format:
  html:
    theme:
      light: [lux, styles.scss]
      dark: [darkly, styles.scss]
    toc: true
    code-fold: true
    code-tools: true
    smooth-scroll: true