project:
  type: website
  output-dir: docs

website:
  title: "Serena Emedeke"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: reflection.qmd
        text: Reflection
      - href: contact.qmd
        text: Contact
      - href: projects/index.qmd
        text: Projects

format:
  html:
    css: styles.css
    toc: true

